### ISSUE TITLE
Duplicated variables

### ISSUE THREAD

**Issue by christianambukita** [primefaces/primereact-sass-theme#7]
`panelHeaderHoverBg`, `panelHeaderHoverBorderColor`, and `panelHeaderTextHoverColor` variables are duplicated.
https://github.com/primefaces/primereact-sass-theme/blob/41b374bf1bef83d534ba08ccbe5742f00f743819/themes/mytheme/variables/_panel.scss#L247

**Comment by melloware** [comment]
Thanks submitted a PR to fix it
