### ISSUE TITLE
Build is failing because mytheme needs additional scss variables

### ISSUE THREAD

**Issue by RSginer** [primefaces/primereact-sass-theme#84]
![Screenshot 2024-10-04 at 14 15 59](https://github.com/user-attachments/assets/5e076337-5c9e-4a86-b3e2-2736f45c2f3e)

The build is failing because the theme "mytheme" needs some additional scss variables.

is fixed in #83

**Comment by melloware** [comment]
Feel free to submit a PR but I don't have commit rights to this project.

**Comment by RSginer** [comment]
PR is open: https://github.com/primefaces/primereact-sass-theme/pull/83 do you know who have rights?

**Comment by melloware** [comment]
only PrimeTek.

**Comment by RSginer** [comment]
@cagataycivici can u check?

**Comment by cagataycivici** [comment]
@mertsincan Can you handle this?

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primereact-sass-theme/pull/83
